### ISSUE TITLE
Not support Laravel 5.7

### ISSUE THREAD

**Issue by KhSayad** [jarektkaczyk/model-locking#13]
after I made an upgrade to laravel v5.7 it through an error:
Undefined index: Sofa\ModelLocking\ModelLock
any way to solve it ?

**Comment by KhSayad** [comment]
solved by adding
parent::boot();
to: src/ModelLock.php

**Comment by Denis4yk** [comment]
But this is NOT the correct way to solve it. So I feel, that this should be reopened.

**Comment by jarektkaczyk** [comment]
PR maybe?

**Comment by jarektkaczyk** [comment]
fixed in https://github.com/jarektkaczyk/model-locking/pull/15
