### ISSUE TITLE
Disable event broadcasting

### ISSUE THREAD

**Issue by sweet-greg** [jarektkaczyk/model-locking#3]
Hi, 
I think it would be good if the configuration had a way to disable event broadcasts.
As of now I can't seem to disable them.

**Comment by jarektkaczyk** [comment]
What if you set channels to empty arrays?

**Comment by svytas** [comment]
Setting channels to empty arrays is not an option if you are broadcasting to pusher.com, because server is returning error "Expected at least one channel" with status 400.
