### ISSUE TITLE
Option to disable tokens

### ISSUE THREAD

**Issue by Braunson** [jarektkaczyk/model-locking#7]
Thoughts on removing the requirement for tokens? In my use case we want to lock something to a certain user, be able to check if locked to the current user (without a token).

**Use Case:**

- User opens edit page for apost
- User is now locked to that post (for 5 minutes)
- User leaves and comes back, we need to check if 
     1. Post is already locked 
     2. If post is locked to existing user

**Comment by Braunson** [comment]
@jarektkaczyk is this repo no longer being maintained?

**Comment by jarektkaczyk** [comment]
merged and tagged
